language: node_js
node_js:
  - "4.0"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_script:
  - mysql -e 'create database foch_testing;'
